substitutions:
  name: PowerProof 600 UPS
  device_description: "Monitor and control any Megatec Protocol based UPS via TTL UART"
  external_components_source: github://nelio12/esphome-megatec-ups@main-dev
  tx_pin: GPIO16
  rx_pin: GPIO17

esphome:
  name: esphome-web-a70578
  friendly_name: NodeMCU Test taller
  min_version: 2025.9.0
  name_add_mac_suffix: false
  comment: ${device_description}
  project:
    name: "nelio12.esphome-megatec-ups"
    version: 1.1.0

esp32:
  variant: esp32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:

# If you don't use Home Assistant please remove this `api` section and uncomment the `mqtt` component!
api:

# mqtt:
#   broker: !secret mqtt_host
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   id: mqtt_client

uart:
  - id: uart_0
    baud_rate: 2400
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
    debug:
      direction: BOTH
      dummy_receiver: false
      after:
        delimiter: "\r"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes);

powermust:
  - id: powermust0
    uart_id: uart_0

binary_sensor:
  - platform: powermust
    powermust_id: powermust0
    utility_fail:
      name: "Utility Fail"
    battery_low:
      name: "Battery Low"
    bypass_active:
      name: "Bypass Active"
    ups_failed:
      name: "UPS Failed"
    ups_type_standby:
      name: "UPS Type Standby"
    test_in_progress:
      name: "Test in progress"
    shutdown_active:
      name: "Shutdown Active"
    beeper_on:
      name: "Beeper On"

sensor:
  - platform: powermust
    powermust_id: powermust0
    grid_voltage:
      name: "Grid Voltage"
    grid_fault_voltage:
      name: "Grid Fault Voltage"
    ac_output_voltage:
      name: "AC Output Voltage"
    ac_output_load_percent:
      name: "AC Output Load Percent"
    grid_frequency:
      name: "Grid Frequency"
    battery_voltage:
      name: "Battery Voltage"
    #temperature:
    #  name: "temperature"
    ac_output_rating_voltage:
      name: "AC Output Rating Voltage"
    ac_output_rating_current:
      name: "AC Output Rating Current"
    battery_rating_voltage:
      name: "Battery Rating Voltage"
    ac_output_rating_frequency:
      name: "AC Output Rating Frequency"

switch:
  - platform: powermust
    powermust_id: powermust0
    beeper:
      name: "Beeper"
    quick_test:
      name: "Quick Test"
    deep_test:
      name: "Deep Test"
    ten_minutes_test:
      name: "10min Test"
    shutdown:
      name: "Apagar UPS en 3 minutos"
      on_command: "S03"
    shutdown_restore:
      name: "Apagar 2 min + Restaurar en 1 hora"
      on_command: "S02R0060"
    cancel_shutdown:
      name: "Cancelar Apagado"

number:
  - platform: template
    name: "Minutos para apagar"
    min_value: 1
    max_value: 99
    step: 1
    optimistic: true
    set_action:
      - lambda: |-
          char cmd[4];
          sprintf(cmd, "S%02d", (int)x);
          ESP_LOGI("powermust", "Enviando apagado en %d minutos: %s", (int)x, cmd);
          id(powermust0).switch_command(cmd);

#text_sensor:
#  - platform: powermust
#    powermust_id: powermust0
#    last_q1:
#      name: "last q1"
#    last_f:
#      name: "last f"